# Generated by Django 4.2.20 on 2025-04-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='base_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
