# Generated by Django 4.2.20 on 2025-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0002_exchange_base_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='filled_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
