# Generated by Django 4.2.20 on 2025-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0003_rename_amount_order_quantity_order_exchange_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='base_url',
            field=models.CharField(blank=True, help_text='Optional custom base URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
