# Generated by Django 4.2.20 on 2025-04-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto_bot', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField()),
                ('features', models.JSONField()),
                ('exchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='crypto_bot.exchange')),
            ],
        ),
    ]
