# Generated by Django 4.2.20 on 2025-04-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradingPair',
        ),
    ]
