# Generated by Django 4.2.20 on 2025-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_delete_tradingpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='pair_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
