# Generated by Django 4.2.20 on 2025-04-24 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0003_exchangeconfig_pair_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
