# Generated by Django 4.2.20 on 2025-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botconfig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
