# Generated by Django 4.2.20 on 2025-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_maintenance', models.BooleanField(default=False)),
                ('expiry_notification', models.BooleanField(default=True)),
                ('policy_change_notification', models.BooleanField(default=True)),
            ],
        ),
    ]
